"""
Executive Order Monitoring Agent

Overview
--------
This script monitors the White House "Executive Orders" page and sends an email
notification whenever a new executive order appears. The email includes:

    • The title of the executive order
    • A link to the order page
    • A short policy analysis generated by an LLM
    • The first substantive paragraph from Section 1 of the order
    • Agent metadata (agent name, model used, token usage, run timestamp)

The script is designed as a lightweight monitoring agent that can be run
periodically (for example, every 15 minutes) via a scheduler such as cron,
GitHub Actions, or another task runner.

The agent maintains local state so that each executive order is only processed
once.

Architecture
------------
The agent follows a simple observe → reason → act architecture.

1. Observe
   The script downloads the Executive Orders index page:

       https://www.whitehouse.gov/presidential-actions/executive-orders/

   It extracts links that correspond to individual executive order detail pages.

2. Detect novelty
   A local JSON file stores previously seen order URLs. If a link is not in the
   stored list, it is considered a newly detected executive order.

3. Extract the first substantive paragraph
   The script attempts two methods:

   Rule-based extraction:
       • Parse the HTML with BeautifulSoup
       • Identify paragraph tags
       • Skip the standard opening line beginning with
         "By the authority vested in me..."
       • Skip section headings such as "Section 1. Purpose."
       • Return the first paragraph of substantive text under Section 1

   GPT fallback extraction:
       If rule-based extraction fails, the page text is passed to the OpenAI
       API to extract the first substantive paragraph from the page content.

4. Generate policy analysis
   The extracted paragraph and capped page text are passed to the OpenAI API
   to produce:

       • A short policy analysis describing the intent and context of the order
       • A cleaned version of the extracted paragraph

   The analysis is constrained to draw only from the text of the order.

5. Send notification email
   The script sends an email via Proton SMTP containing:

       Title
       URL
       Policy analysis
       First substantive paragraph
       Agent metadata

6. Update state
   The processed URL is added to the local state file so the order will not
   trigger another notification in future runs.

State Management
----------------
State is stored in a JSON file:

    agent_state.json

This file contains a rolling list of recently seen executive order URLs.

On the first run, the script initializes the state file with all currently
visible executive orders and does not send any email notifications. This
prevents historical orders from generating alerts.

Subsequent runs only notify for newly detected orders.

Environment Variables
---------------------
The following environment variables must be set before running the script.

OPENAI_API_KEY
    API key for OpenAI. Used for policy analysis and fallback extraction.

PROTON_SMTP_USERNAME
    Proton Mail address used to send notifications.

PROTON_SMTP_TOKEN
    Proton SMTP token generated in Proton Mail settings.

Example shell usage:

    export OPENAI_API_KEY="..."
    export PROTON_SMTP_USERNAME="matthew@fetaverse.net"
    export PROTON_SMTP_TOKEN="..."

Notebook Usage
--------------
In a Jupyter notebook, do not type secrets directly into the script. Instead,
use a separate setup cell such as:

    import os
    from getpass import getpass

    os.environ["OPENAI_API_KEY"] = getpass("OpenAI API key: ")
    os.environ["PROTON_SMTP_USERNAME"] = "matthew@fetaverse.net"
    os.environ["PROTON_SMTP_TOKEN"] = getpass("Proton SMTP token: ")

This keeps secrets out of the script itself and avoids displaying them in cell
output.

Dependencies
------------
The script requires the following Python packages:

    requests
    beautifulsoup4
    openai

Install with:

    pip install requests beautifulsoup4 openai

Execution
---------
The script performs a single monitoring pass when executed:

    python check_whitehouse_eo.py

It is intended to be run periodically by a scheduler.

Example cron schedule (every 15 minutes):

    */15 * * * * python /path/to/check_whitehouse_eo.py

The script can also be run from a Jupyter notebook by importing the main
function:

    from check_whitehouse_eo import check_once
    check_once()

Design Considerations
---------------------
Hybrid extraction strategy:
    Rule-based parsing is used first because it is fast and inexpensive.
    If this fails, the script falls back to an LLM-based extraction method
    which is more robust to layout changes.

Minimal state:
    The script stores only previously seen URLs to prevent duplicate alerts.

Low operational cost:
    LLM calls occur only when processing a newly detected order.

Token safety:
    Page text sent to the model is capped to prevent accidental large token
    usage if page structure changes.

Website robustness:
    The fallback extraction step allows the script to remain functional even
    if the HTML structure of the White House site changes.

Limitations
-----------
• The HTML structure of the White House website may change over time.
• The script assumes that each executive order appears as a linked detail page
  under the Executive Orders index.
• If the page structure changes significantly, rule-based extraction may fail
  and the script will rely on the GPT fallback.

Execution Flow
--------------
Scheduler
    ↓
check_once()
    ↓
Fetch EO index page
    ↓
Detect unseen order URLs
    ↓
Fetch order page
    ↓
Extract first substantive paragraph (rule-based → GPT fallback)
    ↓
Generate policy analysis (LLM)
    ↓
Send email notification
    ↓
Update state file

Author Notes
------------
This script is intentionally lightweight and designed as a clear example of a
monitoring agent architecture:

    observe → detect novelty → extract information → reason → act → store state

It can be extended to:

    • monitor additional presidential actions
    • store data in a database
    • generate richer policy briefings
    • produce dashboards or reports
"""

import os
import json
import re
import smtplib
from email.mime.text import MIMEText
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime, UTC
import requests
from bs4 import BeautifulSoup
from openai import OpenAI

# =========================
# Configuration
# =========================

AGENT_NAME = "whitehouse_executive_order_monitor"
MODEL = "gpt-4.1-mini"

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
PROTON_SMTP_USERNAME = os.getenv("PROTON_SMTP_USERNAME")  # e.g. matthew@fetaverse.net
PROTON_SMTP_TOKEN = os.getenv("PROTON_SMTP_TOKEN")        # Proton SMTP token
TO_EMAIL = "mtushman@gmail.com"

WHITE_HOUSE_INDEX_URL = "https://www.whitehouse.gov/presidential-actions/executive-orders/"
STATE_FILE = Path("agent_state.json")
MAX_RECENT_URLS = 20

SMTP_SERVER = "smtp.protonmail.ch"
SMTP_PORT = 587

USER_AGENT = "EO-Monitor/1.0 (+personal project monitor)"
TIMEOUT = 30

client = OpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None


def fetch_html(url: str) -> str:
    """Download and return HTML for a URL."""
    headers = {"User-Agent": USER_AGENT}
    resp = requests.get(url, headers=headers, timeout=TIMEOUT)
    resp.raise_for_status()
    return resp.text


def load_state() -> Dict:
    """Load the state file or return an empty default state."""
    if not STATE_FILE.exists():
        return {"recent_seen_urls": []}

    with STATE_FILE.open("r", encoding="utf-8") as f:
        state = json.load(f)

    if "recent_seen_urls" not in state or not isinstance(state["recent_seen_urls"], list):
        return {"recent_seen_urls": []}

    return state


def save_state(state: Dict) -> None:
    """Write the current state dictionary to disk."""
    with STATE_FILE.open("w", encoding="utf-8") as f:
        json.dump(state, f, indent=2)


def update_recent_seen_urls(existing_urls: List[str], new_urls: List[str], max_urls: int = MAX_RECENT_URLS) -> List[str]:
    """Merge new URLs into the recent-seen list, de-duplicate, and keep only the newest entries."""
    merged = list(new_urls) + list(existing_urls)

    deduped = []
    seen = set()

    for url in merged:
        if url not in seen:
            seen.add(url)
            deduped.append(url)

    return deduped[:max_urls]


def absolute_url(href: str) -> str:
    """Convert a relative White House link into an absolute URL."""
    if href.startswith("http://") or href.startswith("https://"):
        return href
    return "https://www.whitehouse.gov" + href


def clean_text(text: str) -> str:
    """Normalize whitespace in scraped text."""
    return re.sub(r"\s+", " ", text).strip()


def parse_executive_order_index(html: str) -> List[Dict[str, str]]:
    """Extract executive-order detail links from the index page HTML."""
    soup = BeautifulSoup(html, "html.parser")
    orders = []
    seen = set()

    for a in soup.find_all("a", href=True):
        href = a["href"].strip()
        title = a.get_text(" ", strip=True)

        if not title or not href:
            continue

        # Keep only actual EO detail pages such as:
        # /presidential-actions/2026/02/some-order-title/
        if not re.search(r"/presidential-actions/\d{4}/\d{2}/", href):
            continue

        url = absolute_url(href)

        if url in seen:
            continue

        seen.add(url)
        orders.append({"title": title, "url": url})

    return orders


def extract_paragraph_candidates(html: str) -> List[str]:
    """Collect plausible body paragraphs from an order detail page."""
    soup = BeautifulSoup(html, "html.parser")
    candidates = []

    for p in soup.find_all("p"):
        text = clean_text(p.get_text(" ", strip=True))
        if not text:
            continue
        if len(text) < 80:
            continue

        low = text.lower()

        if low == "share":
            continue
        if low == "the white house":
            continue
        if "published" in low and len(text) < 140:
            continue
        if low == "related":
            continue

        candidates.append(text)

    return candidates


def choose_first_substantive_paragraph(paragraphs: List[str]) -> Optional[str]:
    """
    Select the first real substantive paragraph of the order.

    Skips:
    - the 'By the authority vested...' opening
    - section headings such as 'Section 1. Purpose.'
    """

    if not paragraphs:
        return None

    for p in paragraphs:

        low = p.lower()

        if low.startswith("by the authority vested in me"):
            continue

        if low.startswith("section ") and len(p) < 120:
            continue

        return p

    return None


def extract_paragraph_with_gpt(title: str, url: str, html: str) -> Optional[str]:
    """Use GPT to extract the first substantive paragraph when parsing fails."""
    if not client:
        return None

    soup = BeautifulSoup(html, "html.parser")

    for tag in soup(["script", "style", "noscript"]):
        tag.decompose()

    text = soup.get_text("\n")
    text = re.sub(r"\n{2,}", "\n\n", text).strip()
    text = text[:12000]

    prompt = f"""
You are extracting the first substantive paragraph from a White House executive order page.

Title: {title}
URL: {url}

Page text:
{text}

Instructions:
- Ignore navigation, menus, headers, dates, social sharing, and boilerplate
- Find the first substantive paragraph of the executive order itself
- This often begins with "By the authority vested in me as President..."
- Return strict JSON only

Output format:
{{"first_paragraph": "..."}}
"""

    response = client.responses.create(
        model=MODEL,
        input=prompt,
        text={"format": {"type": "json_object"}},
    )

    text_out = response.output_text.strip()

    try:
        data = json.loads(text_out)
        value = data.get("first_paragraph", "").strip()
        return value or None
    except Exception:
        return None


def extract_first_substantive_paragraph_hybrid(title: str, url: str, html: str) -> str:
    """Try rule-based extraction first, then fall back to GPT extraction."""
    paragraphs = extract_paragraph_candidates(html)
    paragraph = choose_first_substantive_paragraph(paragraphs)

    if paragraph:
        return paragraph

    paragraph = extract_paragraph_with_gpt(title=title, url=url, html=html)
    if paragraph:
        return paragraph

    return "Could not automatically extract a substantive paragraph from the page."


def analyze_policy_and_clean(title: str, url: str, raw_paragraph: str, order_text: str) -> Dict[str, str]:
    """Generate a short policy analysis and clean the extracted paragraph."""
    if not client:
        return {
            "policy": "No OpenAI API key configured; policy analysis skipped.",
            "first_paragraph": raw_paragraph,
            "tokens": 0,
        }

    capped_order_text = order_text[:24000]

    prompt = f"""
You are helping monitor newly published White House executive orders.

Use only the text of the executive order provided below.

Title:
{title}

URL:
{url}

Executive order text:
{capped_order_text}

Extracted first substantive paragraph:
{raw_paragraph}

Task:
Write a concise policy analysis in 2-4 sentences.

Establish the core intent and broader context of the order, including its place
in the administration's policy agenda and any significant shifts it represents
from previous policies. Note the order's own characterization of problems it
aims to address. Draw only from the text of the executive order.

Return strict JSON only.

Output format:
{{"policy": "...", "first_paragraph": "..."}}
"""

    response = client.responses.create(
        model=MODEL,
        input=prompt,
        max_output_tokens=600,
        text={"format": {"type": "json_object"}},
    )

    text_out = response.output_text.strip()

    try:
        data = json.loads(text_out)

        token_count = 0
        if hasattr(response, "usage") and response.usage:
            token_count = response.usage.total_tokens

        return {
            "policy": data["policy"].strip(),
            "first_paragraph": data["first_paragraph"].strip(),
            "tokens": token_count,
        }

    except Exception:
        return {
            "policy": "Policy analysis could not be generated automatically.",
            "first_paragraph": raw_paragraph,
            "tokens": 0,
        }


def extract_visible_text(html: str, char_limit: int = 24000) -> str:
    """Extract visible page text and cap length for safe LLM usage."""
    soup = BeautifulSoup(html, "html.parser")

    for tag in soup(["script", "style", "noscript"]):
        tag.decompose()

    text = soup.get_text("\n")
    text = re.sub(r"\n{2,}", "\n\n", text).strip()
    return text[:char_limit]


def send_email(subject: str, body: str) -> None:
    """Send a plain-text email through Proton SMTP."""
    if not PROTON_SMTP_USERNAME or not PROTON_SMTP_TOKEN:
        raise RuntimeError("Missing PROTON_SMTP_USERNAME or PROTON_SMTP_TOKEN environment variables.")

    msg = MIMEText(body, "plain", "utf-8")
    msg["Subject"] = subject
    msg["From"] = PROTON_SMTP_USERNAME
    msg["To"] = TO_EMAIL

    with smtplib.SMTP(SMTP_SERVER, SMTP_PORT, timeout=30) as server:
        server.starttls()
        server.login(PROTON_SMTP_USERNAME, PROTON_SMTP_TOKEN)
        server.sendmail(PROTON_SMTP_USERNAME, [TO_EMAIL], msg.as_string())


def check_once() -> None:
    """Run one complete monitoring pass and email any newly found orders."""
    state = load_state()
    recent_seen_urls = state.get("recent_seen_urls", [])

    index_html = fetch_html(WHITE_HOUSE_INDEX_URL)
    orders = parse_executive_order_index(index_html)

    if not orders:
        print("No executive orders found on the index page.")
        return

    current_urls = [o["url"] for o in orders]
    new_orders = [o for o in orders if o["url"] not in recent_seen_urls]

    # First run: initialize state without emailing historical items
    if not recent_seen_urls:
        state["recent_seen_urls"] = current_urls[:MAX_RECENT_URLS]
        save_state(state)
        print(f"Initialized state with {len(state['recent_seen_urls'])} recent executive orders. No emails sent.")
        return

    if not new_orders:
        print("No new executive orders.")
        return

    # Process older newly found items first, then newer ones
    for order in reversed(new_orders):
        detail_html = fetch_html(order["url"])

        raw_paragraph = extract_first_substantive_paragraph_hybrid(
            title=order["title"],
            url=order["url"],
            html=detail_html,
        )

        order_text = extract_visible_text(detail_html, char_limit=24000)

        enriched = analyze_policy_and_clean(
            title=order["title"],
            url=order["url"],
            raw_paragraph=raw_paragraph,
            order_text=order_text,
        )

        email_body = f"""New executive order published

Title: {order['title']}
URL: {order['url']}

Policy:
{enriched['policy']}

First substantive paragraph:
{enriched['first_paragraph']}

---

Agent metadata
Agent: {AGENT_NAME}
Model: {MODEL}
Tokens used: {enriched['tokens']}
Run time: {datetime.now(UTC).isoformat()}
"""

        send_email(
            subject=f"New Executive Order: {order['title']}",
            body=email_body,
        )

        print(f"Emailed: {order['title']}")

    # Update rolling recent-URLs state from the current index page plus any newly processed URLs
    state["recent_seen_urls"] = update_recent_seen_urls(
        existing_urls=recent_seen_urls,
        new_urls=current_urls,
        max_urls=MAX_RECENT_URLS,
    )
    save_state(state)


if __name__ == "__main__":
    check_once()